"""
Local bot registry management.

Each channel operator generates and manages their own local registry.
No user IDs are distributed with this package.

Commands:
  generate — Run enumeration + scoring, export IDs above threshold
  add      — Append IDs from a file to the local registry
  check    — Look up a single user ID in the registry
"""

import json
from datetime import datetime, timezone
from pathlib import Path

from ..client import create_client, resolve_channel
from ..config import load_config
from ..enumeration import enumerate_subscribers
from ..scoring import score_user


REGISTRY_VERSION = 1

DEFAULT_REGISTRY_PATH = "registry/known_bots.json"


def _load_registry(path):
    """Load a registry file, returning its data.

    Returns:
        Dict with registry data, or a new empty registry.
    """
    path = Path(path)
    if not path.exists():
        return {
            "version": REGISTRY_VERSION,
            "description": "Local bot registry generated by tg-purge",
            "last_updated": None,
            "channel": None,
            "entries": [],
        }

    try:
        with open(path) as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        raise ValueError(f"Malformed registry file {path}: {e}")

    if not isinstance(data, dict):
        raise ValueError(f"Registry file must be a JSON object, got {type(data).__name__}")

    if "entries" not in data:
        raise ValueError(f"Registry file missing 'entries' key")

    if not isinstance(data["entries"], list):
        raise ValueError(f"Registry 'entries' must be a list")

    return data


def _save_registry(data, path):
    """Save registry data to a JSON file."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    data["last_updated"] = datetime.now(timezone.utc).isoformat()

    with open(path, "w") as f:
        json.dump(data, f, indent=2)
    print(f"Registry saved to {path} ({len(data['entries'])} entries)")


def _existing_ids(data):
    """Return set of user IDs already in the registry."""
    return {entry["user_id"] for entry in data["entries"] if "user_id" in entry}


async def run_generate(args):
    """Generate a registry from channel enumeration + scoring."""
    config = load_config(getattr(args, "config", None))
    if args.session_path:
        config.session_path = args.session_path
    channel_name = config.resolve_channel(args.channel)
    threshold = getattr(args, "threshold", None) or config.threshold
    output_path = getattr(args, "output", None) or DEFAULT_REGISTRY_PATH

    client = await create_client(config)
    try:
        channel = await resolve_channel(client, channel_name)

        def progress(i, total, found):
            if i % 10 == 0:
                print(f"  ...{i}/{total} queries, {found} users found", flush=True)

        print(f"\nEnumerating subscribers...", flush=True)
        result = await enumerate_subscribers(
            client, channel,
            strategy="full",
            delay=config.delay,
            progress_callback=progress,
        )

        all_users = result["users"]
        print(f"Total users enumerated: {len(all_users)}")

        # Score and filter
        entries = []
        for uid, user in all_users.items():
            s, reasons = score_user(user)
            if s >= threshold:
                entries.append({
                    "user_id": uid,
                    "score": s,
                    "date_flagged": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
                    "detection_method": "heuristic_scoring",
                    "notes": "; ".join(reasons),
                })

        print(f"Users above threshold {threshold}: {len(entries)}")

        registry = {
            "version": REGISTRY_VERSION,
            "description": "Local bot registry generated by tg-purge registry generate",
            "last_updated": datetime.now(timezone.utc).isoformat(),
            "channel": channel_name,
            "entries": entries,
        }

        _save_registry(registry, output_path)

    finally:
        await client.disconnect()


async def run_add(args):
    """Add IDs from a file to the local registry."""
    output_path = getattr(args, "registry_path", None) or DEFAULT_REGISTRY_PATH
    registry = _load_registry(output_path)
    existing = _existing_ids(registry)

    ids_file = Path(args.ids_file)
    if not ids_file.exists():
        print(f"Error: file not found: {ids_file}")
        return

    new_count = 0
    with open(ids_file) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                try:
                    uid = int(line)
                    if uid not in existing:
                        registry["entries"].append({
                            "user_id": uid,
                            "score": None,
                            "date_flagged": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
                            "detection_method": "manual_add",
                            "notes": f"Added from {ids_file.name}",
                        })
                        existing.add(uid)
                        new_count += 1
                except ValueError:
                    print(f"  Skipping non-numeric line: {line}")

    print(f"Added {new_count} new entries (skipped {len(existing) - new_count - len(_existing_ids(_load_registry(output_path)))} duplicates)")
    _save_registry(registry, output_path)


async def run_check(args):
    """Check if a user ID exists in the local registry."""
    registry_path = getattr(args, "registry_path", None) or DEFAULT_REGISTRY_PATH

    try:
        registry = _load_registry(registry_path)
    except (ValueError, FileNotFoundError) as e:
        print(f"Error: {e}")
        return

    user_id = int(args.user_id)
    for entry in registry["entries"]:
        if entry.get("user_id") == user_id:
            print(f"FOUND in registry:")
            print(f"  User ID:    {entry['user_id']}")
            print(f"  Score:      {entry.get('score', 'N/A')}")
            print(f"  Flagged:    {entry.get('date_flagged', 'N/A')}")
            print(f"  Method:     {entry.get('detection_method', 'N/A')}")
            print(f"  Notes:      {entry.get('notes', '')}")
            return

    print(f"NOT FOUND: User ID {user_id} is not in the registry at {registry_path}")


async def run(args):
    """Route to the appropriate registry subcommand."""
    action = getattr(args, "registry_action", None)
    if action == "generate":
        await run_generate(args)
    elif action == "add":
        await run_add(args)
    elif action == "check":
        await run_check(args)
    else:
        print("Error: specify a registry action: generate, add, or check")
        print("Usage: tg-purge registry {generate|add|check}")
